/**
 * Import Staten Island campus data from the 云乐 SI Google Spreadsheet export.
 *
 * Usage:
 *   npm run import:si-spreadsheet
 *   npm run import:si-spreadsheet -- --apply
 *
 * Default is dry-run. --apply inserts into Staten Island only (location_id = 2).
 * Brooklyn is never modified. SI is expected empty (or script aborts if SI teachers exist).
 *
 * Source JSON is generated by parsing the xlsx (see scripts/data/si-spreadsheet.json).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { createSupabaseServiceClient } from "@/lib/supabase/service";

const SI_LOCATION_ID = 2;
const APPLY = process.argv.includes("--apply");
const DATA_PATH = join(
  process.cwd(),
  "scripts/data/si-spreadsheet.json",
);

type TeacherRow = {
  key: string;
  first_name: string;
  last_name: string | null;
  phone?: string | null;
  notes?: string | null;
  is_active?: boolean;
};

type StudentRow = {
  key: string;
  first_name: string;
  last_name: string | null;
  phone_number?: string | null;
  dob?: string | null;
  raw_name: string;
};

type ClassRow = {
  key: string;
  sheet: string;
  subject: string;
  teacher_keys: string[];
  lesson_type: "private" | "group" | "trial";
  duration_minutes: number;
  class_track: string;
  room_hint?: string | null;
};

type EnrollmentRow = {
  student_key: string;
  class_key: string;
  lessons: number;
  signup_date: string | null;
  sheet: string;
  notes: string | null;
};

type Payload = {
  location_id: number;
  teachers: TeacherRow[];
  students: StudentRow[];
  classes: ClassRow[];
  enrollments: EnrollmentRow[];
  stats: Record<string, number>;
};

async function main() {
  const payload = JSON.parse(readFileSync(DATA_PATH, "utf8")) as Payload;
  console.log("SI spreadsheet import preview");
  console.log(JSON.stringify(payload.stats, null, 2));
  console.log(
    `Teachers: ${payload.teachers.map((t) => `${t.first_name}${t.last_name ? ` ${t.last_name}` : ""}${t.is_active === false ? " [side]" : ""}`).join(", ")}`,
  );
  console.log(
    `Classes: ${payload.classes.map((c) => `${c.subject} (${c.teacher_keys.join("+")})`).join(", ")}`,
  );

  if (!APPLY) {
    console.log("\nDry-run only. Re-run with --apply to write Staten Island data.");
    return;
  }

  const supabase = createSupabaseServiceClient();

  const { count: existingTeachers, error: existingErr } = await supabase
    .from("teachers")
    .select("id", { count: "exact", head: true })
    .eq("location_id", SI_LOCATION_ID);

  if (existingErr) {
    throw new Error(`Could not check SI teachers: ${existingErr.message}`);
  }
  if ((existingTeachers ?? 0) > 0) {
    throw new Error(
      `Staten Island already has ${existingTeachers} teachers. Aborting to avoid duplicates. Wipe SI first if re-importing.`,
    );
  }

  const { data: rooms, error: roomsErr } = await supabase
    .from("rooms")
    .select("id, room_number")
    .eq("location_id", SI_LOCATION_ID);
  if (roomsErr) throw new Error(roomsErr.message);
  const roomByNumber = new Map(
    (rooms ?? []).map((r) => [r.room_number.trim().toLowerCase(), r.id]),
  );

  // Teachers
  const teacherIdByKey = new Map<string, number>();
  for (const teacher of payload.teachers) {
    const { data, error } = await supabase
      .from("teachers")
      .insert({
        first_name: teacher.first_name,
        last_name: teacher.last_name,
        phone_number: teacher.phone ?? null,
        notes: teacher.notes ?? null,
        is_active: teacher.is_active !== false,
        location_id: SI_LOCATION_ID,
      })
      .select("id")
      .single();
    if (error) throw new Error(`Teacher ${teacher.key}: ${error.message}`);
    teacherIdByKey.set(teacher.key, data.id);
  }
  console.log(`Inserted ${teacherIdByKey.size} teachers`);

  // Students
  const studentIdByKey = new Map<string, number>();
  const studentChunks: StudentRow[][] = [];
  for (let i = 0; i < payload.students.length; i += 50) {
    studentChunks.push(payload.students.slice(i, i + 50));
  }
  for (const chunk of studentChunks) {
    const { data, error } = await supabase
      .from("students")
      .insert(
        chunk.map((s) => ({
          "first name": s.first_name,
          "last name": s.last_name,
          experience: s.phone_number
            ? `Contact: ${s.phone_number}`
            : null,
          dob: s.dob ?? null,
          is_active: true,
          location_id: SI_LOCATION_ID,
        })),
      )
      .select('id, "first name", "last name"');
    if (error) throw new Error(`Students insert: ${error.message}`);
    // Match back by order within chunk
    for (let i = 0; i < chunk.length; i++) {
      const row = data?.[i];
      if (!row) throw new Error("Student insert missing returned row");
      studentIdByKey.set(chunk[i].key, row.id);
    }
  }
  console.log(`Inserted ${studentIdByKey.size} students`);

  // Classes + class_teachers
  const classIdByKey = new Map<string, number>();
  for (const cls of payload.classes) {
    const primaryKey = cls.teacher_keys[0];
    const primaryId = teacherIdByKey.get(primaryKey);
    if (primaryId == null) {
      throw new Error(`Missing teacher ${primaryKey} for class ${cls.key}`);
    }
    const roomId = cls.room_hint
      ? (roomByNumber.get(cls.room_hint.trim().toLowerCase()) ?? null)
      : null;

    const { data, error } = await supabase
      .from("classes")
      .insert({
        subject: cls.subject,
        teacher_id: primaryId,
        room_id: roomId,
        duration_minutes: cls.duration_minutes,
        lesson_type: cls.lesson_type,
        class_track: cls.class_track,
        is_active: true,
        location_id: SI_LOCATION_ID,
      })
      .select("id")
      .single();
    if (error) throw new Error(`Class ${cls.key}: ${error.message}`);
    classIdByKey.set(cls.key, data.id);

    const { error: ctErr } = await supabase.from("class_teachers").insert(
      cls.teacher_keys.map((key, index) => {
        const tid = teacherIdByKey.get(key);
        if (tid == null) throw new Error(`Missing co-teacher ${key}`);
        return {
          class_id: data.id,
          teacher_id: tid,
          is_primary: index === 0,
        };
      }),
    );
    if (ctErr) throw new Error(`class_teachers ${cls.key}: ${ctErr.message}`);
  }
  console.log(`Inserted ${classIdByKey.size} classes`);

  // Enrollments + credits
  let enrollmentCount = 0;
  let creditGrants = 0;
  for (const enr of payload.enrollments) {
    const studentId = studentIdByKey.get(enr.student_key);
    const classId = classIdByKey.get(enr.class_key);
    if (studentId == null || classId == null) {
      throw new Error(
        `Missing ids for enrollment ${enr.student_key} / ${enr.class_key}`,
      );
    }

    const { data: enrollment, error } = await supabase
      .from("enrollments")
      .insert({
        "student id": studentId,
        "class id": classId,
        is_active: true,
        created_date: enr.signup_date,
        grade_level: "G0-2",
      })
      .select("id")
      .single();
    if (error) {
      throw new Error(
        `Enrollment ${enr.student_key}@${enr.class_key}: ${error.message}`,
      );
    }
    enrollmentCount += 1;
    void enrollment;

    if (enr.lessons > 0) {
      const { error: creditErr } = await supabase.rpc(
        "grant_student_class_credits",
        {
          p_student_id: studentId,
          p_class_id: classId,
          p_credits: enr.lessons,
          p_reason: `SI spreadsheet import (${enr.sheet})`,
        },
      );
      if (creditErr) {
        throw new Error(
          `Credits ${enr.student_key}@${enr.class_key}: ${creditErr.message}`,
        );
      }
      creditGrants += 1;
    }
  }

  console.log(
    `Inserted ${enrollmentCount} enrollments; granted credits on ${creditGrants}`,
  );
  console.log("Done. Staten Island import complete.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
