-- Admin event posts with photo/video attachments.
CREATE TABLE public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  body text NOT NULL,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.event_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  media_type text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_media_type_check
    CHECK (media_type IN ('image', 'video'))
);

CREATE INDEX event_media_event_id_idx ON public.event_media (event_id);
CREATE INDEX events_created_at_idx ON public.events (created_at DESC);

COMMENT ON TABLE public.events IS 'School announcements and highlights posted by admins.';
COMMENT ON TABLE public.event_media IS 'Images and videos attached to an event post.';

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'event-media',
  'event-media',
  true,
  52428800,
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/webm',
    'video/quicktime'
  ]::text[]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE POLICY "Public read event media files"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'event-media');
