-- One-off overrides for recurring class schedules (e.g. move a single week's occurrence).
CREATE TABLE public.class_schedule_exceptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id bigint NOT NULL REFERENCES public.class_schedules (id) ON DELETE CASCADE,
  original_date date NOT NULL,
  override_date date NOT NULL,
  schedule_start_time time NOT NULL,
  schedule_end_time time NOT NULL,
  is_cancelled boolean NOT NULL DEFAULT false,
  CONSTRAINT class_schedule_exceptions_times_check
    CHECK (is_cancelled OR schedule_end_time > schedule_start_time),
  CONSTRAINT class_schedule_exceptions_unique_occurrence
    UNIQUE (schedule_id, original_date)
);

CREATE INDEX class_schedule_exceptions_schedule_id_idx
  ON public.class_schedule_exceptions (schedule_id);

CREATE INDEX class_schedule_exceptions_override_date_idx
  ON public.class_schedule_exceptions (override_date);

COMMENT ON TABLE public.class_schedule_exceptions IS
  'Per-date overrides for a recurring class schedule (reschedule or cancel one occurrence).';
