-- Multiple meeting times per class (e.g. Piano group meets Mon + Wed).
CREATE TABLE public.class_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  is_recurring boolean NOT NULL DEFAULT true,
  schedule_day_of_week smallint,
  schedule_date date,
  schedule_start_time time NOT NULL,
  schedule_end_time time NOT NULL,
  CONSTRAINT class_schedules_day_check
    CHECK (schedule_day_of_week IS NULL OR (schedule_day_of_week >= 0 AND schedule_day_of_week <= 6)),
  CONSTRAINT class_schedules_times_check
    CHECK (schedule_end_time > schedule_start_time),
  CONSTRAINT class_schedules_recurrence_check
    CHECK (
      (is_recurring = true AND schedule_day_of_week IS NOT NULL AND schedule_date IS NULL)
      OR (is_recurring = false AND schedule_date IS NOT NULL AND schedule_day_of_week IS NULL)
    )
);

CREATE INDEX class_schedules_class_id_idx ON public.class_schedules (class_id);

COMMENT ON TABLE public.class_schedules IS 'One or more weekly or one-time meeting slots for a class.';
COMMENT ON COLUMN public.class_schedules.schedule_day_of_week IS '0=Sunday through 6=Saturday; used when is_recurring is true.';

INSERT INTO public.class_schedules (
  class_id,
  is_recurring,
  schedule_day_of_week,
  schedule_date,
  schedule_start_time,
  schedule_end_time
)
SELECT
  id,
  is_recurring,
  schedule_day_of_week,
  schedule_date,
  schedule_start_time,
  schedule_end_time
FROM public.classes
WHERE schedule_start_time IS NOT NULL
  AND schedule_end_time IS NOT NULL;

-- Example: Piano classes meet twice a week.
INSERT INTO public.class_schedules (
  class_id,
  is_recurring,
  schedule_day_of_week,
  schedule_start_time,
  schedule_end_time
)
SELECT
  c.id,
  true,
  ((c.schedule_day_of_week + 2) % 7),
  TIME '16:00:00',
  (TIME '16:00:00' + (COALESCE(c.duration_minutes, 60) * INTERVAL '1 minute'))::time
FROM public.classes c
WHERE lower(c.subject) LIKE '%piano%'
  AND c.schedule_day_of_week IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.class_schedules cs
    WHERE cs.class_id = c.id
      AND cs.schedule_day_of_week = ((c.schedule_day_of_week + 2) % 7)
      AND cs.schedule_start_time = TIME '16:00:00'
  );

ALTER TABLE public.classes DROP CONSTRAINT IF EXISTS classes_schedule_recurrence_check;
ALTER TABLE public.classes DROP CONSTRAINT IF EXISTS classes_schedule_times_check;
ALTER TABLE public.classes DROP CONSTRAINT IF EXISTS classes_schedule_day_of_week_check;

ALTER TABLE public.classes
  DROP COLUMN IF EXISTS is_recurring,
  DROP COLUMN IF EXISTS schedule_day_of_week,
  DROP COLUMN IF EXISTS schedule_date,
  DROP COLUMN IF EXISTS schedule_start_time,
  DROP COLUMN IF EXISTS schedule_end_time;
