-- Assign class_track from subject for existing classes (matches lib/class-track.ts inferClassTrackFromSubject).
UPDATE public.classes
SET class_track = CASE
  WHEN lower(subject) LIKE '%voice%'
    OR lower(subject) LIKE '%choir%'
    OR lower(subject) LIKE '%singing%'
    THEN 'vocal'
  WHEN lower(subject) LIKE '%songwriting%'
    OR lower(subject) LIKE '%composition%'
    THEN 'composition'
  WHEN lower(subject) LIKE '%dance%'
    OR lower(subject) LIKE '%ballet%'
    OR lower(subject) LIKE '%tap%'
    OR lower(subject) LIKE '%hip hop%'
    OR lower(subject) LIKE '%rhythms%'
    THEN 'dance'
  WHEN lower(subject) LIKE '%theory%'
    OR lower(subject) LIKE '%theater%'
    OR lower(subject) LIKE '%theatre%'
    OR lower(subject) LIKE '%ensemble%'
    THEN 'music_education'
  WHEN lower(subject) LIKE '%piano%'
    OR lower(subject) LIKE '%violin%'
    OR lower(subject) LIKE '%viola%'
    OR lower(subject) LIKE '%cello%'
    OR lower(subject) LIKE '%guitar%'
    OR lower(subject) LIKE '%drums%'
    OR lower(subject) LIKE '%percussion%'
    OR lower(subject) LIKE '%flute%'
    OR lower(subject) LIKE '%saxophone%'
    OR lower(subject) LIKE '%trumpet%'
    OR lower(subject) LIKE '%clarinet%'
    OR lower(subject) LIKE '%ukulele%'
    THEN 'instrumental'
  ELSE 'other'
END
WHERE class_track IS NULL;
